<?xml version="1.0" encoding="UTF-8"?>
<definitions xmlns="http://schemas.xmlsoap.org/wsdl/"
             xmlns:tns="http://fanavacard.ir/services"
             xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
             xmlns:xsd="http://www.w3.org/2001/XMLSchema"
             targetNamespace="http://fanavacard.ir/services"
             name="FanavaService">
  <types>
    <xsd:schema targetNamespace="http://fanavacard.ir/services" elementFormDefault="qualified">
      <xsd:element name="Verify">
        <xsd:complexType>
          <xsd:sequence>
            <xsd:element name="Token" type="xsd:string"/>
          </xsd:sequence>
        </xsd:complexType>
      </xsd:element>
      <xsd:element name="VerifyResponse">
        <xsd:complexType>
          <xsd:sequence>
            <xsd:element name="Status" type="xsd:int"/>
            <xsd:element name="Amount" type="xsd:long"/>
          </xsd:sequence>
        </xsd:complexType>
      </xsd:element>
    </xsd:schema>
  </types>
  <message name="VerifySoapIn">
    <part name="parameters" element="tns:Verify"/>
  </message>
  <message name="VerifySoapOut">
    <part name="parameters" element="tns:VerifyResponse"/>
  </message>
  <portType name="FanavaSoap">
    <operation name="Verify">
      <input message="tns:VerifySoapIn"/>
      <output message="tns:VerifySoapOut"/>
    </operation>
  </portType>
  <binding name="FanavaSoapBinding" type="tns:FanavaSoap">
    <soap:binding transport="http://schemas.xmlsoap.org/soap/http"/>
    <operation name="Verify">
      <soap:operation soapAction="http://fanavacard.ir/services/Verify" style="document"/>
      <input><soap:body use="literal"/></input>
      <output><soap:body use="literal"/></output>
    </operation>
  </binding>
  <service name="FanavaService">
    <port name="FanavaSoap" binding="tns:FanavaSoapBinding">
      <soap:address location="http://localhost:8080/fanava/services"/>
    </port>
  </service>
</definitions>
