<?xml version="1.0" encoding="UTF-8"?>
<definitions xmlns="http://schemas.xmlsoap.org/wsdl/"
             xmlns:tns="http://sadad.shaparak.ir/services"
             xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
             xmlns:xsd="http://www.w3.org/2001/XMLSchema"
             targetNamespace="http://sadad.shaparak.ir/services"
             name="SadadPaymentService">
  <types>
    <xsd:schema targetNamespace="http://sadad.shaparak.ir/services" elementFormDefault="qualified">
      <xsd:element name="VerifyRequest">
        <xsd:complexType>
          <xsd:sequence>
            <xsd:element name="Token" type="xsd:string"/>
            <xsd:element name="SignData" type="xsd:string" minOccurs="0"/>
          </xsd:sequence>
        </xsd:complexType>
      </xsd:element>
      <xsd:element name="VerifyResponse">
        <xsd:complexType>
          <xsd:sequence>
            <xsd:element name="ResCode" type="xsd:int"/>
            <xsd:element name="Amount" type="xsd:long"/>
            <xsd:element name="Description" type="xsd:string"/>
            <xsd:element name="RetrivalReferenceNumber" type="xsd:string"/>
            <xsd:element name="SystemTraceNo" type="xsd:string"/>
          </xsd:sequence>
        </xsd:complexType>
      </xsd:element>
    </xsd:schema>
  </types>
  <message name="VerifySoapIn">
    <part name="parameters" element="tns:VerifyRequest"/>
  </message>
  <message name="VerifySoapOut">
    <part name="parameters" element="tns:VerifyResponse"/>
  </message>
  <portType name="SadadSoap">
    <operation name="Verify">
      <input message="tns:VerifySoapIn"/>
      <output message="tns:VerifySoapOut"/>
    </operation>
  </portType>
  <binding name="SadadSoapBinding" type="tns:SadadSoap">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <operation name="Verify">
      <soap:operation soapAction="http://sadad.shaparak.ir/services/Verify"/>
      <input><soap:body use="literal"/></input>
      <output><soap:body use="literal"/></output>
    </operation>
  </binding>
  <service name="SadadPaymentService">
    <port name="SadadSoap" binding="tns:SadadSoapBinding">
      <soap:address location="http://localhost:8080/sadad/services"/>
    </port>
  </service>
</definitions>
